class Gometalinter < Formula
  desc "Concurrently run Go lint tools and normalise their output."
  homepage "https://github.com/alecthomas/gometalinter"
  url "https://github.com/alecthomas/gometalinter/releases/download/v2.0.8/gometalinter-2.0.8-darwin-amd64.tar.gz"
  version "2.0.8"
  sha256 "d75916592c4d596ec615bdbb752cde097001c3f58c79e85b24732af5a351ec95"

  def install
    bin.install "gometalinter"
    bin.install "gocyclo"
    bin.install "nakedret"
    bin.install "misspell"
    bin.install "gosec"
    bin.install "golint"
    bin.install "ineffassign"
    bin.install "goconst"
    bin.install "errcheck"
    bin.install "maligned"
    bin.install "unconvert"
    bin.install "dupl"
    bin.install "structcheck"
    bin.install "varcheck"
    bin.install "safesql"
    bin.install "deadcode"
    bin.install "lll"
    bin.install "goimports"
    bin.install "gotype"
    bin.install "gosimple"
    bin.install "megacheck"
    bin.install "staticcheck"
    bin.install "unused"
    bin.install "interfacer"
    bin.install "unparam"
    bin.install "gochecknoinits"
    bin.install "gochecknoglobals"
  end
end
